export const themes = {
  light: {
    name: "Light",
    background: "#ffffff",
    text: "#000000",
    primary: "#0d6efd",
    secondary: "#6c757d",
  },
  dark: {
    name: "Dark",
    background: "#1e1e2f",
    text: "#ffffff",
    primary: "#4e9f3d",
    secondary: "#555",
  },
  cupcake: {
    name: "Cupcake",
    background: "#fdf0f5",
    text: "#4b0082",
    primary: "#ff69b4",
    secondary: "#ffb6c1",
  },
  bumblebee: {
    name: "Bumblebee",
    background: "#fff8c6",
    text: "#333300",
    primary: "#ffd700",
    secondary: "#ffcc00",
  },
  emerald: {
    name: "Emerald",
    background: "#def7ec",
    text: "#065f46",
    primary: "#10b981",
    secondary: "#047857",
  },
  corporate: {
    name: "Corporate",
    background: "#e5e7eb",
    text: "#111827",
    primary: "#3b82f6",
    secondary: "#6b7280",
  },
  synthwave: {
    name: "Synthwave",
    background: "#2d0035",
    text: "#f0f",
    primary: "#ff56f6",
    secondary: "#0ff",
  },
  retro: {
    name: "Retro",
    background: "#fff1a5",
    text: "#27272a",
    primary: "#ef4444",
    secondary: "#facc15",
  },
  cyberpunk: {
    name: "Cyberpunk",
    background: "#2d2d2d",
    text: "#00ffcc",
    primary: "#ff007f",
    secondary: "#3f3f3f",
  },
  valentine: {
    name: "Valentine",
    background: "#fef2f2",
    text: "#9d174d",
    primary: "#f472b6",
    secondary: "#fbcfe8",
  },
  halloween: {
    name: "Halloween",
    background: "#1a202c",
    text: "#f97316",
    primary: "#f59e0b",
    secondary: "#ef4444",
  },
  garden: {
    name: "Garden",
    background: "#e0f2f1",
    text: "#1b5e20",
    primary: "#34d399",
    secondary: "#065f46",
  },
  forest: {
    name: "Forest",
    background: "#2e3b2b",
    text: "#ffffff",
    primary: "#4caf50",
    secondary: "#388e3c",
  },
  aqua: {
    name: "Aqua",
    background: "#e0f7fa",
    text: "#00796b",
    primary: "#00bcd4",
    secondary: "#4dd0e1",
  },
  lofi: {
    name: "Lofi",
    background: "#f9fafb",
    text: "#1f2937",
    primary: "#6b7280",
    secondary: "#9ca3af",
  },
  pastel: {
    name: "Pastel",
    background: "#fef3c7",
    text: "#7c3aed",
    primary: "#fbbf24",
    secondary: "#a78bfa",
  },
  fantasy: {
    name: "Fantasy",
    background: "#f3e8ff",
    text: "#6b21a8",
    primary: "#c084fc",
    secondary: "#a855f7",
  },
  wireframe: {
    name: "Wireframe",
    background: "#f9fafb",
    text: "#111827",
    primary: "#9ca3af",
    secondary: "#d1d5db",
  },
  black: {
    name: "Black",
    background: "#000000",
    text: "#ffffff",
    primary: "#1f2937",
    secondary: "#4b5563",
  },
  luxury: {
    name: "Luxury",
    background: "#1e293b",
    text: "#facc15",
    primary: "#bfae48",
    secondary: "#cbd5e1",
  },
  dracula: {
    name: "Dracula",
    background: "#282a36",
    text: "#f8f8f2",
    primary: "#bd93f9",
    secondary: "#ff79c6",
  },
  cmyk: {
    name: "CMYK",
    background: "#ffffff",
    text: "#000000",
    primary: "#00aaff",
    secondary: "#ff00aa",
  },
  autumn: {
    name: "Autumn",
    background: "#fffaf0",
    text: "#78350f",
    primary: "#d97706",
    secondary: "#b45309",
  },
  business: {
    name: "Business",
    background: "#f3f4f6",
    text: "#1f2937",
    primary: "#2563eb",
    secondary: "#4b5563",
  },
  acid: {
    name: "Acid",
    background: "#fef9c3",
    text: "#a21caf",
    primary: "#ec4899",
    secondary: "#facc15",
  },
  lemonade: {
    name: "Lemonade",
    background: "#fef3c7",
    text: "#78350f",
    primary: "#fde047",
    secondary: "#fbbf24",
  },
  night: {
    name: "Night",
    background: "#0f172a",
    text: "#e5e7eb",
    primary: "#1e40af",
    secondary: "#475569",
  },
  coffee: {
    name: "Coffee",
    background: "#2e2725",
    text: "#f5f0e1",
    primary: "#e6a157",
    secondary: "#5d4037",
  },
  winter: {
    name: "Winter",
    background: "#f0f9ff",
    text: "#1e3a8a",
    primary: "#38bdf8",
    secondary: "#60a5fa",
  },
  dim: {
    name: "Dim",
    background: "#202124",
    text: "#e8eaed",
    primary: "#8ab4f8",
    secondary: "#5f6368",
  },
  nord: {
    name: "Nord",
    background: "#2e3440",
    text: "#d8dee9",
    primary: "#88c0d0",
    secondary: "#81a1c1",
  },
  sunset: {
    name: "Sunset",
    background: "#ffe4e1",
    text: "#4b0082",
    primary: "#ff7f50",
    secondary: "#ff1493",
  },
};
